#ifndef CARPI_QT_SETTINGS_GLOBAL_H
#define CARPI_QT_SETTINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGS_LIBRARY)
#  define SETTINGS_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGS_EXPORT Q_DECL_IMPORT
#endif

#endif //CARPI_QT_SETTINGS_GLOBAL_H
