
#ifndef CARPI_QT_BLUETOOTH_GLOBAL_H
#define CARPI_QT_BLUETOOTH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLUETOOTH_LIBRARY)
#  define BLUETOOTH_EXPORT Q_DECL_EXPORT
#else
#  define BLUETOOTH_EXPORT Q_DECL_IMPORT
#endif

#endif //CARPI_QT_BLUETOOTH_GLOBAL_H
